import MainHeader from "@/components/main-header/main-header";
import "./globals.css";

export const metadata = {
  title: "Food platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainHeader />

        {children}
      </body>
    </html>
  );
}
